version: 2.1

orbs:
  ci: bigcommerce/internal@volatile
  php: bigcommerce/internal-php@volatile

jobs:
  codesniffer:
    parameters:
      php-version:
        type: string
        default: "8.0"
    executor:
      name: php/php
      php-version: << parameters.php-version >>
    steps:
      - ci/pre-setup
      - php/install-extensions:
          additional_apt_packages: ''
          additional_php_extensions: ''
          additional_pecl_extensions: ''
      - php/composer-install
      - run: ./vendor/bin/phpcs --standard=PSR2 --ignore=src/Grphp/grpc.stubs.php src
  cs-fixer:
    parameters:
      php-version:
        type: string
        default: "8.0"
    executor:
      name: php/php
      php-version: << parameters.php-version >>
    steps:
      - ci/pre-setup
      - php/install-extensions:
          additional_apt_packages: ''
          additional_php_extensions: ''
          additional_pecl_extensions: ''
      - php/composer-install
      - run: ./vendor/bin/php-cs-fixer fix --diff --dry-run -v

workflows:
  version: 2
  full:
    jobs:
      - php/phpunit-tests:
          configuration: "phpunit.xml.dist"
          pecl_extensions: "grpc"
          matrix:
            parameters:
              php-version: [ "8.0", "8.1", "8.2" ]
      - codesniffer:
          matrix:
            parameters:
              php-version: [ "8.0", "8.1", "8.2" ]
      - cs-fixer:
          matrix:
            parameters:
              php-version: [ "8.0", "8.1", "8.2" ]
