<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grphp/test/Things.proto

namespace Grphp\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Protobuf type <code>grphp.test.GetThingResp</code>
 */
class GetThingResp extends \Google\Protobuf\Internal\Message
{
    /**
     * <code>.grphp.test.Thing thing = 1;</code>
     */
    private $thing = null;

    public function __construct() {
        \GPBMetadata\Grphp\Test\Things::initOnce();
        parent::__construct();
    }

    /**
     * <code>.grphp.test.Thing thing = 1;</code>
     */
    public function getThing()
    {
        return $this->thing;
    }

    /**
     * <code>.grphp.test.Thing thing = 1;</code>
     */
    public function setThing(&$var)
    {
        GPBUtil::checkMessage($var, \Grphp\Test\Thing::class);
        $this->thing = $var;
    }

}

