<?php
/**
 * Copyright (c) 2017-present, BigCommerce Pty. Ltd. All rights reserved
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grphp/test/Things.proto

namespace Grphp\Test;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>grphp.test.GetThingResp</code>
 */
class GetThingResp extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.grphp.test.Thing thing = 1;</code>
     */
    private $thing = null;

    public function __construct() {
        \GPBMetadata\Grphp\Test\Thing::initOnce();
        parent::__construct();
    }

    /**
     * Generated from protobuf field <code>.grphp.test.Thing thing = 1;</code>
     * @return \Grphp\Test\Thing
     */
    public function getThing()
    {
        return $this->thing;
    }

    /**
     * Generated from protobuf field <code>.grphp.test.Thing thing = 1;</code>
     * @param \Grphp\Test\Thing $var
     * @return $this
     */
    public function setThing($var)
    {
        GPBUtil::checkMessage($var, \Grphp\Test\Thing::class);
        $this->thing = $var;

        return $this;
    }

}

