<?php
/**
 * Copyright (c) 2017-present, BigCommerce Pty. Ltd. All rights reserved
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
 * documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
 * COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grphp/test/Things.proto

namespace Grphp\Test;

use Exception;
use Google\Protobuf\Internal\Message;
use Google\Protobuf\Internal\GPBUtil;
use GPBMetadata\Grphp\Test\Things;

/**
 * Generated from protobuf message <code>grphp.test.GetThingReq</code>
 */
class GetThingReq extends Message
{
    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     */
    protected int $id = 0;

    /**
     * Constructor.
     *
     * @param array|null $data {
     *     Optional. Data for populating the Message object.
     *
     */
    public function __construct(array $data = null)
    {
        Things::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @return int
     */
    public function getId(): int
    {
        return $this->id;
    }

    /**
     * Generated from protobuf field <code>uint64 id = 1;</code>
     * @param int $var
     * @return $this
     * @throws Exception
     */
    public function setId(int $var): GetThingReq
    {
        GPBUtil::checkUint64($var);
        $this->id = $var;

        return $this;
    }

}
