<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grphp/test/Things.proto

namespace GPBMetadata\Grphp\Test;

class Things
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
            return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8010a1767727068702f746573742f5468696e67732e70726f746f120a" .
            "67727068702e7465737422210a055468696e67120a0a0269641801200128" .
            "04120c0a046e616d6518022001280922190a0b4765745468696e67526571" .
            "120a0a02696418012001280422300a0c4765745468696e67526573701220" .
            "0a057468696e6718012001280b32112e67727068702e746573742e546869" .
            "6e6732490a065468696e6773123f0a084765745468696e6712172e677270" .
            "68702e746573742e4765745468696e675265711a182e67727068702e7465" .
            "73742e4765745468696e67526573702200620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

